import { registerFormation } from '../stores/formationStore'

registerFormation({
  id: 'devops',
  name: 'Admin Systeme & DevOps',
  nameEn: 'System Admin & DevOps',
  accent: '#3b82f6',
  accentHover: '#60a5fa',
  accentGlow: 'rgba(59, 130, 246, 0.1)',
  accentLight: '#2563eb',
  accentHoverLight: '#1d4ed8',
  accentGlowLight: 'rgba(37, 99, 235, 0.08)',
  icon: 'Container',
  description: '38 chapitres couvrant Linux, Git, Docker, Kubernetes, Cloud, CI/CD, Monitoring, Securite et SRE.',
  descriptionEn: '38 chapters covering Linux, Git, Docker, Kubernetes, Cloud, CI/CD, Monitoring, Security and SRE.',
  cliSimulatorType: 'terminal',
  defaultFirstChapterSlug: 'introduction-linux',
  programs: [
    { id: 'devops-1', name: 'Fondations Linux', nameEn: 'Linux Foundations', color: '#f97316', description: 'Installation, commandes, permissions, systemd, logs, scripting bash', descriptionEn: 'Installation, commands, permissions, systemd, logs, bash scripting', chapterCount: 6 },
    { id: 'devops-2', name: 'Reseaux, Git & Scripting', nameEn: 'Networking, Git & Scripting', color: '#8b5cf6', description: 'OSI, IP/CIDR, DNS, reverse proxy, Git, GitHub/GitLab, Python', descriptionEn: 'OSI, IP/CIDR, DNS, reverse proxy, Git, GitHub/GitLab, Python', chapterCount: 7 },
    { id: 'devops-3', name: 'Conteneurs & Docker', nameEn: 'Containers & Docker', color: '#10b981', description: 'Conteneurs, Dockerfile, Docker Compose, volumes, securite, production', descriptionEn: 'Containers, Dockerfile, Docker Compose, volumes, security, production', chapterCount: 6 },
    { id: 'devops-4', name: 'Kubernetes', nameEn: 'Kubernetes', color: '#ef4444', description: 'Architecture, Pods, Services, Ingress, Helm, Secrets, Autoscaling', descriptionEn: 'Architecture, Pods, Services, Ingress, Helm, Secrets, Autoscaling', chapterCount: 6 },
    { id: 'devops-5', name: 'Cloud & Infrastructure as Code', nameEn: 'Cloud & Infrastructure as Code', color: '#3b82f6', description: 'AWS, Azure, GCP, Terraform, CloudFormation, bonnes pratiques', descriptionEn: 'AWS, Azure, GCP, Terraform, CloudFormation, best practices', chapterCount: 6 },
    { id: 'devops-6', name: 'CI/CD, Monitoring, Securite & SRE', nameEn: 'CI/CD, Monitoring, Security & SRE', color: '#f59e0b', description: 'GitHub Actions, GitLab CI, Prometheus, ELK, DevSecOps, SRE', descriptionEn: 'GitHub Actions, GitLab CI, Prometheus, ELK, DevSecOps, SRE', chapterCount: 7 },
  ],
  tools: [
    { path: 'flashcards', labelFr: 'Flashcards', labelEn: 'Flashcards', icon: 'Layers', descriptionFr: 'Fiches DevOps : Linux, Docker, Kubernetes, CI/CD, Cloud et plus.', descriptionEn: 'DevOps cards: Linux, Docker, Kubernetes, CI/CD, Cloud and more.' },
    { path: 'simulateur-cli', labelFr: 'Simulateur Terminal', labelEn: 'Terminal Simulator', icon: 'Terminal', descriptionFr: 'Labs guides Bash, Docker et Kubectl pour pratiquer en conditions reelles.', descriptionEn: 'Guided Bash, Docker and Kubectl labs for real-world practice.' },
    { path: 'glossaire', labelFr: 'Glossaire DevOps', labelEn: 'DevOps Glossary', icon: 'BookA', descriptionFr: 'Termes DevOps : conteneurs, orchestration, CI/CD, cloud, IaC et plus.', descriptionEn: 'DevOps terms: containers, orchestration, CI/CD, cloud, IaC and more.' },
    { path: 'fiches-pdf', labelFr: 'Fiches PDF', labelEn: 'PDF Sheets', icon: 'FileDown', descriptionFr: 'Exporte des fiches de revision par chapitre au format PDF pour reviser hors ligne.', descriptionEn: 'Export revision sheets per chapter as PDF for offline study.' },
    { path: 'quiz-aleatoire', labelFr: 'Quiz Aleatoire', labelEn: 'Random Quiz', icon: 'Shuffle', color: '#f59e0b', descriptionFr: 'Genere un quiz personnalise avec des questions aleatoires sur les programmes de ton choix.', descriptionEn: 'Generate a custom quiz with random questions from programs of your choice.' },
    { path: 'revision-espacee', labelFr: 'Revision Espacee', labelEn: 'Spaced Repetition', icon: 'Clock', color: '#a855f7', descriptionFr: 'Algorithme SM-2 : cartes planifiees selon ta memoire pour une retention optimale.', descriptionEn: 'SM-2 algorithm: cards scheduled according to your memory for optimal retention.' },
    { path: 'export', labelFr: 'Exporter CSV', labelEn: 'Export CSV', icon: 'FileDown', descriptionFr: 'Exporte toutes tes donnees de progression au format CSV pour analyse ou sauvegarde.', descriptionEn: 'Export all your progress data as CSV for analysis or backup.' },
  ],
  games: [
    {
      id: 'match-port', titleFr: 'Match the Port', titleEn: 'Match the Port',
      descriptionFr: 'Associe les services et outils DevOps a leurs numeros de port.',
      descriptionEn: 'Match DevOps services and tools to their port numbers.',
      icon: 'Layers', path: 'mini-jeux/match-port', difficulty: '3 niveaux', difficultyEn: '3 levels',
      color: '#6366f1', storageKey: 'nr_minigame_match',
    },
    {
      id: 'coming-soon-1', titleFr: 'Bientot disponible', titleEn: 'Coming Soon',
      descriptionFr: 'De nouveaux mini-jeux DevOps arrivent bientot.',
      descriptionEn: 'New DevOps mini-games coming soon.',
      icon: 'Lock', path: '', difficulty: '—', difficultyEn: '—',
      color: 'var(--text-muted)', storageKey: '', disabled: true,
    },
  ],
  features: [
    { path: 'parcours', labelFr: 'Parcours Adaptatif', labelEn: 'Adaptive Path', icon: 'Compass' },
    { path: 'defis', labelFr: 'Defis Hebdo', labelEn: 'Weekly Challenges', icon: 'Target' },
    { path: 'formateur', labelFr: 'Formateur', labelEn: 'Trainer', icon: 'Users' },
    { path: 'quiz-communautaire', labelFr: 'Quiz Communautaire', labelEn: 'Community Quiz', icon: 'Users' },
  ],
  heroVisualItems: [
    { icon: 'Terminal', label: 'Linux & Bash', sub: 'Fondations', subEn: 'Foundations', color: '#f97316' },
    { icon: 'Container', label: 'Docker', sub: 'Conteneurs', subEn: 'Containers', color: '#10b981' },
    { icon: 'Server', label: 'Kubernetes', sub: 'Orchestration', subEn: 'Orchestration', color: '#ef4444' },
    { icon: 'Cloud', label: 'Cloud & IaC', sub: 'Infrastructure', subEn: 'Infrastructure', color: '#3b82f6' },
  ],
  stats: [
    { value: '38', labelFr: 'chapitres', labelEn: 'chapters' },
    { value: '500+', labelFr: 'questions', labelEn: 'questions' },
    { value: '20h+', labelFr: 'de contenu', labelEn: 'of content' },
    { value: '100%', labelFr: 'gratuit', labelEn: 'free' },
  ],
})
