import { registerFormation } from '../stores/formationStore'

registerFormation({
  id: 'reseaux',
  name: 'Reseaux & CCNA',
  nameEn: 'Networking & CCNA',
  accent: '#00e5a0',
  accentHover: '#00c98b',
  accentGlow: 'rgba(0, 229, 160, 0.1)',
  accentLight: '#059669',
  accentHoverLight: '#047857',
  accentGlowLight: 'rgba(5, 150, 105, 0.08)',
  icon: 'Network',
  description: '49 chapitres couvrant 100% du CCNA 200-301 : reseaux, switching, routage, services IP, securite, wireless et automation.',
  descriptionEn: '49 chapters covering 100% of CCNA 200-301: networking, switching, routing, IP services, security, wireless and automation.',
  cliSimulatorType: 'cisco',
  defaultFirstChapterSlug: 'modele-osi',
  programs: [
    { id: 'programme-1', name: 'Fondamentaux Reseau', nameEn: 'Network Fundamentals', color: '#00e5a0', description: 'OSI, composants, topologies, cablage, switching, IPv4, TCP/UDP, IPv6', descriptionEn: 'OSI, components, topologies, cabling, switching, IPv4, TCP/UDP, IPv6', chapterCount: 11 },
    { id: 'programme-2', name: 'Acces Reseau & Connectivite', nameEn: 'Network Access & Connectivity', color: '#6366f1', description: 'VLANs, STP, inter-VLAN, EtherChannel, routage statique, OSPF', descriptionEn: 'VLANs, STP, inter-VLAN, EtherChannel, static routing, OSPF', chapterCount: 10 },
    { id: 'programme-3', name: 'Services IP & Entreprise', nameEn: 'IP Services & Enterprise', color: '#f59e0b', description: 'NAT/PAT, DHCP, DNS, NTP, SNMP, Syslog, QoS, ACL', descriptionEn: 'NAT/PAT, DHCP, DNS, NTP, SNMP, Syslog, QoS, ACL', chapterCount: 11 },
    { id: 'programme-4', name: 'Securite', nameEn: 'Security', color: '#e11d48', description: 'Concepts securite, Layer 2, VPN IPsec, AAA', descriptionEn: 'Security concepts, Layer 2, IPsec VPN, AAA', chapterCount: 4 },
    { id: 'programme-5', name: 'Wireless', nameEn: 'Wireless', color: '#8b5cf6', description: 'Wi-Fi, architectures, WLAN, securite wireless, WLC', descriptionEn: 'Wi-Fi, architectures, WLAN, wireless security, WLC', chapterCount: 6 },
    { id: 'programme-6', name: 'Automation & Programmabilite', nameEn: 'Automation & Programmability', color: '#06b6d4', description: 'SDN, APIs REST, outils de config, JSON, AI/ML', descriptionEn: 'SDN, REST APIs, config tools, JSON, AI/ML', chapterCount: 7 },
  ],
  tools: [
    { path: 'calculatrice', labelFr: 'Calculatrice Subnetting', labelEn: 'Subnetting Calculator', icon: 'Calculator', descriptionFr: 'Calcule adresses reseau, broadcast, plages d\'hotes, masques et wildcard.', descriptionEn: 'Calculate network addresses, broadcast, host ranges, masks and wildcards.' },
    { path: 'flashcards', labelFr: 'Flashcards', labelEn: 'Flashcards', icon: 'Layers', descriptionFr: '140 fiches de revision : OSI, ACL, NAT, VPN, QoS, BGP, MPLS, SDN, cybersecurite et plus.', descriptionEn: '140 revision cards: OSI, ACL, NAT, VPN, QoS, BGP, MPLS, SDN, cybersecurity and more.' },
    { path: 'simulateur-cli', labelFr: 'Simulateur CLI Cisco', labelEn: 'Cisco CLI Simulator', icon: 'Terminal', descriptionFr: '49 labs guides, 4 niveaux (debutant a expert) : routage, OSPF, ACL, config complete.', descriptionEn: '49 guided labs, 4 levels (beginner to expert): routing, OSPF, ACL, full config.' },
    { path: 'exercices-subnetting', labelFr: 'Exercices Subnetting', labelEn: 'Subnetting Exercises', icon: 'Brain', color: '#f59e0b', descriptionFr: 'Problemes generes aleatoirement : adresses reseau, broadcast, masques et CIDR.', descriptionEn: 'Randomly generated problems: network addresses, broadcast, masks and CIDR.' },
    { path: 'glossaire', labelFr: 'Glossaire Reseau', labelEn: 'Network Glossary', icon: 'BookA', descriptionFr: '149 termes : OSI, IP, routage, VLAN, securite, services et plus.', descriptionEn: '149 terms: OSI, IP, routing, VLAN, security, services and more.' },
    { path: 'comparateur', labelFr: 'Comparateur Protocoles', labelEn: 'Protocol Comparator', icon: 'ArrowLeftRight', color: '#6366f1', descriptionFr: 'Compare 25+ protocoles reseau cote a cote : ports, couches OSI, securite et performances.', descriptionEn: 'Compare 25+ network protocols side by side: ports, OSI layers, security and performance.' },
    { path: 'plan-adressage', labelFr: 'Plan Adressage IP', labelEn: 'IP Addressing Plan', icon: 'Map', color: '#3b82f6', descriptionFr: 'Generateur VLSM : decoupe un reseau en sous-reseaux avec visualisation et export PDF.', descriptionEn: 'VLSM generator: divide a network into subnets with visualization and PDF export.' },
    { path: 'visualiseur-paquet', labelFr: 'Visualiseur Paquet', labelEn: 'Packet Visualizer', icon: 'PackageOpen', color: '#a855f7', descriptionFr: 'Visualise l\'encapsulation et decapsulation OSI etape par etape avec 5 scenarios.', descriptionEn: 'Visualize OSI encapsulation and decapsulation step by step with 5 scenarios.' },
    { path: 'fiches-pdf', labelFr: 'Fiches PDF', labelEn: 'PDF Sheets', icon: 'FileDown', descriptionFr: 'Exporte des fiches de revision par chapitre au format PDF pour reviser hors ligne.', descriptionEn: 'Export revision sheets per chapter as PDF for offline study.' },
    { path: 'quiz-aleatoire', labelFr: 'Quiz Aleatoire', labelEn: 'Random Quiz', icon: 'Shuffle', color: '#f59e0b', descriptionFr: 'Genere un quiz personnalise avec des questions aleatoires sur les programmes de ton choix.', descriptionEn: 'Generate a custom quiz with random questions from programs of your choice.' },
    { path: 'schemas-reseau', labelFr: 'Schemas Reseau', labelEn: 'Network Diagrams', icon: 'Network', color: '#3b82f6', descriptionFr: 'Cree des schemas reseau interactifs avec drag-and-drop : routeurs, switchs, PCs et liens.', descriptionEn: 'Create interactive network diagrams with drag-and-drop: routers, switches, PCs and links.' },
    { path: 'revision-espacee', labelFr: 'Revision Espacee', labelEn: 'Spaced Repetition', icon: 'Clock', color: '#a855f7', descriptionFr: 'Algorithme SM-2 : 140 cartes planifiees selon ta memoire pour une retention optimale.', descriptionEn: 'SM-2 algorithm: 140 cards scheduled according to your memory for optimal retention.' },
    { path: 'export', labelFr: 'Exporter CSV', labelEn: 'Export CSV', icon: 'FileDown', descriptionFr: 'Exporte toutes tes donnees de progression au format CSV pour analyse ou sauvegarde.', descriptionEn: 'Export all your progress data as CSV for analysis or backup.' },
  ],
  games: [
    {
      id: 'route-packet', titleFr: 'Route the Packet', titleEn: 'Route the Packet',
      descriptionFr: 'Guide le paquet a travers le reseau en evitant les pare-feux, liens casses et boucles.',
      descriptionEn: 'Guide the packet through the network while avoiding firewalls, broken links and loops.',
      icon: 'Map', path: 'mini-jeux/route-packet', difficulty: '10 niveaux', difficultyEn: '10 levels',
      color: '#00e5a0', storageKey: 'nr_minigame_route',
    },
    {
      id: 'match-port', titleFr: 'Match the Port', titleEn: 'Match the Port',
      descriptionFr: 'Associe les services reseau a leurs numeros de port dans ce jeu de memoire.',
      descriptionEn: 'Match network services to their port numbers in this memory game.',
      icon: 'Layers', path: 'mini-jeux/match-port', difficulty: '3 niveaux', difficultyEn: '3 levels',
      color: '#6366f1', storageKey: 'nr_minigame_match',
    },
    {
      id: 'build-header', titleFr: 'Build the Header', titleEn: 'Build the Header',
      descriptionFr: 'Reconstitue les en-tetes Ethernet, IP et TCP en placant les champs dans le bon ordre.',
      descriptionEn: 'Rebuild Ethernet, IP and TCP headers by placing the fields in the correct order.',
      icon: 'Puzzle', path: 'mini-jeux/build-header', difficulty: '3 rounds', difficultyEn: '3 rounds',
      color: '#f59e0b', storageKey: 'nr_minigame_header',
    },
  ],
  features: [
    { path: 'parcours', labelFr: 'Parcours Adaptatif', labelEn: 'Adaptive Path', icon: 'Compass' },
    { path: 'defis', labelFr: 'Defis Hebdo', labelEn: 'Weekly Challenges', icon: 'Target' },
    { path: 'formateur', labelFr: 'Formateur', labelEn: 'Trainer', icon: 'Users' },
    { path: 'quiz-communautaire', labelFr: 'Quiz Communautaire', labelEn: 'Community Quiz', icon: 'Users' },
  ],
  heroVisualItems: [
    { icon: 'Monitor', label: 'OSI Model', sub: '7 couches', subEn: '7 layers', color: '#00e5a0' },
    { icon: 'Globe', label: 'IPv4 / IPv6', sub: 'Adressage', subEn: 'Addressing', color: '#3b82f6' },
    { icon: 'Shield', label: 'VLAN & STP', sub: 'Segmentation', subEn: 'Segmentation', color: '#f59e0b' },
    { icon: 'Terminal', label: 'DNS & DHCP', sub: 'Services', subEn: 'Services', color: '#a855f7' },
  ],
  stats: [
    { value: '49', labelFr: 'chapitres', labelEn: 'chapters' },
    { value: '690+', labelFr: 'questions', labelEn: 'questions' },
    { value: '25h+', labelFr: 'de contenu', labelEn: 'of content' },
    { value: '100%', labelFr: 'gratuit', labelEn: 'free' },
  ],
})
