import {
  Network, Container, Calculator, Brain, ArrowLeftRight, Map, PackageOpen,
  Layers, Terminal, BookA, FileDown, Shuffle, Clock, Compass, Target,
  Users, Gamepad2, Flame, Swords, Flag, Monitor, Globe, Shield, Cloud,
  Server, Puzzle, Lock, Star, Trophy, BookOpen, BarChart3, GraduationCap,
  LayoutDashboard, Award, User, StickyNote, Wrench, ChevronDown, Search,
  Sun, Moon, LogOut, Menu, X, ArrowRight, ArrowLeft, PieChart, MessageSquare,
  FileText, Share2, type LucideIcon,
} from 'lucide-react'

const iconMap: Record<string, LucideIcon> = {
  Network,
  Container,
  Calculator,
  Brain,
  ArrowLeftRight,
  Map,
  PackageOpen,
  Layers,
  Terminal,
  BookA,
  FileDown,
  Shuffle,
  Clock,
  Compass,
  Target,
  Users,
  Gamepad2,
  Flame,
  Swords,
  Flag,
  Monitor,
  Globe,
  Shield,
  Cloud,
  Server,
  Puzzle,
  Lock,
  Star,
  Trophy,
  BookOpen,
  BarChart3,
  GraduationCap,
  LayoutDashboard,
  Award,
  User,
  StickyNote,
  Wrench,
  ChevronDown,
  Search,
  Sun,
  Moon,
  LogOut,
  Menu,
  X,
  ArrowRight,
  ArrowLeft,
  PieChart,
  MessageSquare,
  FileText,
  Share2,
}

export function getIcon(name: string): LucideIcon {
  return iconMap[name] || Network
}

export default iconMap
